buildscript {
    repositories {
        google()
        mavenCentral()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:8.2.0'
    }
}

apply plugin: 'com.android.application'

android {
    namespace 'com.ramin.chess'
    compileSdk 34

    defaultConfig {
        applicationId 'com.ramin.chess'
        minSdk 21
        targetSdk 34
        versionCode 1504
        versionName "15.0.4"
    }

    buildTypes {
        debug {
            // استفاده از امضای پیش‌فرض اندروید
        }
        release {
            minifyEnabled false
        }
    }
}

repositories {
    google()
    mavenCentral()
}
